### ISSUE TITLE
Requirements?

### ISSUE THREAD

**Issue by dustinromey** [vokal/pg-table-markdown#6]
Would be helpful to have some requirements.  I found on ubuntu 14.04 that I had to first run:
`sudo apt-get install python-dev`

And then when I tried to run the code, I got the following error:
`psycopg2.ProgrammingError: function json_agg(record) does not exist
LINE 14:     SELECT      JSON_AGG(table_schema_info.*)`
Which I assume means you need to be running postgres 9.4+.  I'm running 9.1, so this won't work (and totally reasonable on your part.  I need to upgrade!)

Cool idea.  I'll come back to it when I get upgraded.

**Comment by foresmac** [comment]
Great feedback. We may be able to adjust the code to send the optimized query if we can introspect the version of Postgres running. Still, it's definitely a good idea to document that the current version only works on 9.4+.

**Comment by foresmac** [comment]
I also think `python-dev` is probably a requirement for `psycopg2`, since it uses C bridging to call into the Postgres libs. Definitely worth noting.

**Comment by dustinromey** [comment]
That's exactly what I ran into with python-dev.

**Comment by foresmac** [comment]
@dustinromey FYI, v1.0.4 will work on older versions of Postgres. That's available via PyPi now. I'm also adding a note about `psycopg2` reqs shortly.

**Comment by dustinromey** [comment]
Worked like a charm.  Thanks.
