### ISSUE TITLE
Sample output

### ISSUE THREAD

**Issue by ghost** [vokal/pg-table-markdown#8]
Why is there no sample output in the README.md? I dont know what exactly does "markdown documentation for table schema" mean, though the project seems interesting and rather than have to try it, I'd like to see sample output. 

I currently use sadisplay for generating ER diagrams for my Postgres DB schema and the word documentation in your project caught my attention. Thanks!

**Comment by foresmac** [comment]
Thanks for the feedback. I agree this might be useful. To set your expectations, this generates markdown tables that document the current schema, including column name, type, default value, and null ability for all your tables. It doesn't generate ERDs. It's designed to serve as a reference for current table state for projects that manage SQL directly. 

I hope that helps for now. I'll work on getting a sample output set up soon; probably over the holidays.

**Comment by ghost** [comment]
Thanks!
